# Generated by Django 2.2.6 on 2019-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='microbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastTemperatureReading', models.IntegerField()),
                ('lastLightReading', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='microbitsummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatureMean', models.IntegerField()),
                ('lightMean', models.IntegerField()),
            ],
        ),
    ]