# Generated by Django 2.2.6 on 2019-10-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbit',
            name='lastLightReading',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='microbit',
            name='lastTemperatureReading',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='microbitsummary',
            name='lightMean',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='microbitsummary',
            name='temperatureMean',
            field=models.CharField(max_length=6),
        ),
    ]
