# Generated by Django 2.2.6 on 2019-10-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191006_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbit',
            name='microbitID',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
