# Generated by Django 2.2.6 on 2019-10-14 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_microbit_microbitid'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbit',
            name='timeOfReading',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='microbitsummary',
            name='numberOfMicrobits',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microbitsummary',
            name='timeOfReading',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
