# Generated by Django 2.2.6 on 2019-10-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191014_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbit',
            name='microbitID',
            field=models.CharField(max_length=6),
        ),
    ]
